
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

command_line:
  - cover:
      name: RolloTisch
      unique_id: rollotisch
      command_open: python3 /config/RolloL2H.py -i "IP-Addr" -m "MAC_Addr" up
      command_close: python3 /config/RolloL2H.py -i "IP-Addr" -m "MAC_Addr" down
      command_stop: python3 /config/RolloL2H.py -i "IP-Addr" -m "MAC_Addr" stop

      